#!/usr/bin/env python3
"""
README Generator Agent
Creates comprehensive README with weather statistics
Auto-updates daily with fresh data
"""
import json
import os
from datetime import datetime, timedelta

class ReadmeGenerator:
    def __init__(self):
        script_dir = os.path.dirname(os.path.abspath(__file__))
        self.base_dir = os.path.dirname(script_dir)

    def generate_readme(self, weather_data, summary):
        """Generate complete README.md content"""
        today = datetime.now().strftime("%Y-%m-%d")
        current_time = datetime.now().strftime("%H:%M")

        # Get country breakdown
        country_stats = self._get_country_stats(weather_data)

        # Get weather condition distribution
        weather_dist = self._get_weather_distribution(weather_data)

        readme = f"""# 🌍 Global Weather Tracker

> Automated daily weather data collection from {summary.get('total_cities', 0)} cities worldwide!

## 📊 Today's Summary

| Metric | Value |
|--------|-------|
| **Date** | {today} |
| **Total Cities Tracked** | {summary.get('total_cities', 0)} |
| **Average Temperature** | {summary.get('avg_temperature', 0)}°C |
| **Average Humidity** | {summary.get('avg_humidity', 0)}% |
| **Hottest City** | {summary.get('hottest_city', 'N/A')} |
| **Coldest City** | {summary.get('coldest_city', 'N/A')} |

---

## 🗺️ Global Coverage

| Continent/Region | Countries | Cities |
|-----------------|-----------|--------|
{self._format_continent_table(country_stats)}

---

## 🌡️ Temperature Distribution

```
{self._create_temperature_bar(summary.get('avg_temperature', 0))}
```

---

## ☁️ Weather Conditions Today

{self._format_weather_conditions(weather_dist)}

---

## 📁 Data Files

### Main Data Files
- `data/weather_data_{today}.json` - Complete daily data
- `data/latest_weather.json` - Most recent data
- `data/cities.json` - City database with coordinates

### Country Files
- `data/countries/*.json` - Individual country data

### Historical Data
- `data/cities_csv/*.csv` - Per-city historical records

---

## 🔄 Automation

This repository is automatically updated daily via GitHub Actions!

- **Schedule**: Daily at 9:00 AM UTC
- **Data Source**: Open-Meteo API (Free, no API key)
- **Coverage**: {summary.get('total_cities', 0)} cities across {len(country_stats)} countries

### How It Works

1. GitHub Actions triggers daily
2. Python script fetches weather from Open-Meteo API
3. Data is processed and saved to JSON/CSV files
4. README is auto-generated with statistics
5. Changes are auto-committed to repository

---

## 📈 Historical Data

The repository collects weather data daily, creating a valuable dataset for:
- Climate analysis
- Weather pattern tracking
- Historical comparisons
- Data science projects

---

## 🛠️ Technologies Used

| Technology | Purpose |
|------------|---------|
| Python | Data fetching and processing |
| Open-Meteo API | Weather data source |
| GitHub Actions | Daily automation |
| JSON/CSV | Data storage |

---

## 🤖 Contributing

This is an automated repository but contributions are welcome!

- Add new cities to `data/cities.json`
- Improve data processing
- Add new data sources

---

*Last updated: {today} at {current_time}*
*Auto-generated by Global Weather Tracker*
"""

        return readme

    def _get_country_stats(self, weather_data):
        """Get statistics by country"""
        countries = {}
        for city in weather_data:
            country = city.get("country", "Unknown")
            if country not in countries:
                countries[country] = {"count": 0, "total_temp": 0, "temps": []}

            countries[country]["count"] += 1
            temp = city.get("current", {}).get("temperature_2m")
            if temp is not None:
                countries[country]["total_temp"] += temp
                countries[country]["temps"].append(temp)

        return countries

    def _get_weather_distribution(self, weather_data):
        """Get distribution of weather conditions"""
        conditions = {}
        weather_codes = {
            0: "Clear sky",
            1: "Mainly clear",
            2: "Partly cloudy",
            3: "Overcast",
            45: "Fog",
            48: "Depositing rime fog",
            51: "Light drizzle",
            53: "Moderate drizzle",
            55: "Dense drizzle",
            61: "Slight rain",
            63: "Moderate rain",
            65: "Heavy rain",
            71: "Slight snow",
            73: "Moderate snow",
            75: "Heavy snow",
            80: "Slight rain showers",
            81: "Moderate rain showers",
            82: "Violent rain showers",
            95: "Thunderstorm",
            96: "Thunderstorm with hail",
            99: "Thunderstorm with heavy hail"
        }

        for city in weather_data:
            code = city.get("current", {}).get("weather_code", 0)
            condition = weather_codes.get(code, f"Code {code}")
            conditions[condition] = conditions.get(condition, 0) + 1

        return conditions

    def _format_continent_table(self, country_stats):
        """Format country statistics as markdown table"""
        lines = []
        for country, stats in sorted(country_stats.items(), key=lambda x: x[1]["count"], reverse=True):
            avg_temp = sum(stats["temps"]) / len(stats["temps"]) if stats["temps"] else 0
            lines.append(f"| {country} | {stats['count']} | {avg_temp:.1f}°C |")
        return "\n".join(lines[:15])  # Top 15 countries

    def _create_temperature_bar(self, avg_temp):
        """Create a visual temperature bar"""
        # Map temperature to a scale
        if avg_temp < 0:
            emoji = "❄️"
        elif avg_temp < 10:
            emoji = "🌡️"
        elif avg_temp < 20:
            emoji = "🌤️"
        elif avg_temp < 30:
            emoji = "☀️"
        else:
            emoji = "🔥"

        return f"Average: {avg_temp:.1f}°C {emoji}"

    def _format_weather_conditions(self, weather_dist):
        """Format weather conditions as list"""
        lines = []
        for condition, count in sorted(weather_dist.items(), key=lambda x: x[1], reverse=True):
            lines.append(f"- **{condition}**: {count} cities")
        return "\n".join(lines[:10])

    def save_readme(self, content):
        """Save README.md to base directory"""
        readme_path = os.path.join(self.base_dir, "README.md")
        with open(readme_path, 'w') as f:
            f.write(content)
        print(f"  📝 Updated README.md")
        return readme_path

if __name__ == "__main__":
    gen = ReadmeGenerator()
    print("  📖 README Generator initialized")